// Code generated by Mir codegen. DO NOT EDIT.

package bcmpbevents

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/bcmpb/types"
	types3 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/statepb/types"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func NewBlock(destModule stdtypes.ModuleID, block *types.Block) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_NewBlock{
					NewBlock: &types2.NewBlock{
						Block: block,
					},
				},
			},
		},
	}
}

func NewChain(destModule stdtypes.ModuleID, blocks []*types.Block) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_NewChain{
					NewChain: &types2.NewChain{
						Blocks: blocks,
					},
				},
			},
		},
	}
}

func GetChainRequest(destModule stdtypes.ModuleID, requestId string, sourceModule stdtypes.ModuleID, endBlockId uint64, sourceBlockIds []uint64) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_GetChainRequest{
					GetChainRequest: &types2.GetChainRequest{
						RequestId:      requestId,
						SourceModule:   sourceModule,
						EndBlockId:     endBlockId,
						SourceBlockIds: sourceBlockIds,
					},
				},
			},
		},
	}
}

func GetChainResponse(destModule stdtypes.ModuleID, requestId string, success bool, chain []*types.Block) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_GetChainResponse{
					GetChainResponse: &types2.GetChainResponse{
						RequestId: requestId,
						Success:   success,
						Chain:     chain,
					},
				},
			},
		},
	}
}

func RegisterCheckpoint(destModule stdtypes.ModuleID, blockId uint64, state *types3.State) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_RegisterCheckpoint{
					RegisterCheckpoint: &types2.RegisterCheckpoint{
						BlockId: blockId,
						State:   state,
					},
				},
			},
		},
	}
}

func GetChainToHeadRequest(destModule stdtypes.ModuleID, sourceModule stdtypes.ModuleID) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_GetChainToHeadRequest{
					GetChainToHeadRequest: &types2.GetChainToHeadRequest{
						SourceModule: sourceModule,
					},
				},
			},
		},
	}
}

func GetChainToHeadResponse(destModule stdtypes.ModuleID, chain []*types.Block, checkpointState *types3.State) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_GetChainToHeadResponse{
					GetChainToHeadResponse: &types2.GetChainToHeadResponse{
						Chain:           chain,
						CheckpointState: checkpointState,
					},
				},
			},
		},
	}
}

func InitBlockchain(destModule stdtypes.ModuleID, initialState *types3.State) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcm{
			Bcm: &types2.Event{
				Type: &types2.Event_InitBlockchain{
					InitBlockchain: &types2.InitBlockchain{
						InitialState: initialState,
					},
				},
			},
		},
	}
}
