// Code generated by Mir codegen. DO NOT EDIT.

package synchronizerpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/blockchainpb/synchronizerpb/events"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func SyncRequest(m dsl.Module, destModule stdtypes.ModuleID, orphanBlock *types.Block, leaveNodeIds []uint64) {
	dsl.EmitMirEvent(m, events.SyncRequest(destModule, orphanBlock, leaveNodeIds))
}
