// Code generated by Mir codegen. DO NOT EDIT.

package synchronizerpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/synchronizerpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	dsl1 "github.com/filecoin-project/mir/pkg/pb/messagepb/dsl"
	types1 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for processing net messages.

func UponMessageReceived[W types.Message_TypeWrapper[M], M any](m dsl.Module, handler func(from stdtypes.NodeID, msg *M) error) {
	dsl1.UponMessageReceived[*types1.Message_Synchronizer](m, func(from stdtypes.NodeID, msg *types.Message) error {
		w, ok := msg.Type.(W)
		if !ok {
			return nil
		}

		return handler(from, w.Unwrap())
	})
}

func UponChainRequestReceived(m dsl.Module, handler func(from stdtypes.NodeID, requestId string, blockId uint64, leaveNodeIds []uint64) error) {
	UponMessageReceived[*types.Message_ChainRequest](m, func(from stdtypes.NodeID, msg *types.ChainRequest) error {
		return handler(from, msg.RequestId, msg.BlockId, msg.LeaveNodeIds)
	})
}

func UponChainResponseReceived(m dsl.Module, handler func(from stdtypes.NodeID, requestId string, found bool, chain []*types2.Block) error) {
	UponMessageReceived[*types.Message_ChainResponse](m, func(from stdtypes.NodeID, msg *types.ChainResponse) error {
		return handler(from, msg.RequestId, msg.Found, msg.Chain)
	})
}
