// Code generated by Mir codegen. DO NOT EDIT.

package broadcastpbevents

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/broadcastpb/types"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func NewBlock(destModule stdtypes.ModuleID, block *types.Block) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Broadcast{
			Broadcast: &types2.Event{
				Type: &types2.Event_NewBlock{
					NewBlock: &types2.NewBlock{
						Block: block,
					},
				},
			},
		},
	}
}
