// Code generated by Mir codegen. DO NOT EDIT.

package pbeventpb

import (
	reflect "reflect"
)

func (*Event) ReflectTypeOptions() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf((*Event_Bcm)(nil)),
		reflect.TypeOf((*Event_Miner)(nil)),
		reflect.TypeOf((*Event_Broadcast)(nil)),
		reflect.TypeOf((*Event_Synchronizer)(nil)),
		reflect.TypeOf((*Event_Application)(nil)),
		reflect.TypeOf((*Event_Bcinterceptor)(nil)),
	}
}
