// Code generated by Mir codegen. DO NOT EDIT.

package minerpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/blockchainpb/minerpb/events"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/payloadpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func BlockRequest(m dsl.Module, destModule stdtypes.ModuleID, headId uint64, payload *types.Payload) {
	dsl.EmitMirEvent(m, events.BlockRequest(destModule, headId, payload))
}

func NewHead(m dsl.Module, destModule stdtypes.ModuleID, headId uint64) {
	dsl.EmitMirEvent(m, events.NewHead(destModule, headId))
}
