// Code generated by Mir codegen. DO NOT EDIT.

package broadcastpbmsgs

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/broadcastpb/types"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func NewBlockMessage(destModule stdtypes.ModuleID, block *types.Block) *types1.Message {
	return &types1.Message{
		DestModule: destModule,
		Type: &types1.Message_Broadcast{
			Broadcast: &types2.Message{
				Type: &types2.Message_NewBlock{
					NewBlock: &types2.NewBlockMessage{
						Block: block,
					},
				},
			},
		},
	}
}
