// Code generated by Mir codegen. DO NOT EDIT.

package interceptorpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/blockchainpb/interceptorpb/events"
	types1 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/statepb/types"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func TreeUpdate(m dsl.Module, destModule stdtypes.ModuleID, blocks []*types.Block, headId uint64) {
	dsl.EmitMirEvent(m, events.TreeUpdate(destModule, blocks, headId))
}

func StateUpdate(m dsl.Module, destModule stdtypes.ModuleID, state *types1.State) {
	dsl.EmitMirEvent(m, events.StateUpdate(destModule, state))
}
