// Code generated by Mir codegen. DO NOT EDIT.

package interceptorpbevents

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/interceptorpb/types"
	types3 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/statepb/types"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func TreeUpdate(destModule stdtypes.ModuleID, blocks []*types.Block, headId uint64) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcinterceptor{
			Bcinterceptor: &types2.Event{
				Type: &types2.Event_TreeUpdate{
					TreeUpdate: &types2.TreeUpdate{
						Blocks: blocks,
						HeadId: headId,
					},
				},
			},
		},
	}
}

func StateUpdate(destModule stdtypes.ModuleID, state *types3.State) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Bcinterceptor{
			Bcinterceptor: &types2.Event{
				Type: &types2.Event_StateUpdate{
					StateUpdate: &types2.StateUpdate{
						State: state,
					},
				},
			},
		},
	}
}
