// Code generated by Mir codegen. DO NOT EDIT.

package broadcastpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/blockchainpb/broadcastpb/events"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func NewBlock(m dsl.Module, destModule stdtypes.ModuleID, block *types.Block) {
	dsl.EmitMirEvent(m, events.NewBlock(destModule, block))
}
