// Code generated by Mir codegen. DO NOT EDIT.

package broadcastpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/broadcastpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	dsl1 "github.com/filecoin-project/mir/pkg/pb/messagepb/dsl"
	types1 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for processing net messages.

func UponMessageReceived[W types.Message_TypeWrapper[M], M any](m dsl.Module, handler func(from stdtypes.NodeID, msg *M) error) {
	dsl1.UponMessageReceived[*types1.Message_Broadcast](m, func(from stdtypes.NodeID, msg *types.Message) error {
		w, ok := msg.Type.(W)
		if !ok {
			return nil
		}

		return handler(from, w.Unwrap())
	})
}

func UponNewBlockMessageReceived(m dsl.Module, handler func(from stdtypes.NodeID, block *types2.Block) error) {
	UponMessageReceived[*types.Message_NewBlock](m, func(from stdtypes.NodeID, msg *types.NewBlockMessage) error {
		return handler(from, msg.Block)
	})
}
