// Code generated by Mir codegen. DO NOT EDIT.

package synchronizerpbmsgs

import (
	types1 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/synchronizerpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func ChainRequest(destModule stdtypes.ModuleID, requestId string, blockId uint64, leaveNodeIds []uint64) *types.Message {
	return &types.Message{
		DestModule: destModule,
		Type: &types.Message_Synchronizer{
			Synchronizer: &types1.Message{
				Type: &types1.Message_ChainRequest{
					ChainRequest: &types1.ChainRequest{
						RequestId:    requestId,
						BlockId:      blockId,
						LeaveNodeIds: leaveNodeIds,
					},
				},
			},
		},
	}
}

func ChainResponse(destModule stdtypes.ModuleID, requestId string, found bool, chain []*types2.Block) *types.Message {
	return &types.Message{
		DestModule: destModule,
		Type: &types.Message_Synchronizer{
			Synchronizer: &types1.Message{
				Type: &types1.Message_ChainResponse{
					ChainResponse: &types1.ChainResponse{
						RequestId: requestId,
						Found:     found,
						Chain:     chain,
					},
				},
			},
		},
	}
}
