// Code generated by Mir codegen. DO NOT EDIT.

package pbmessagepb

import (
	reflect "reflect"
)

func (*Message) ReflectTypeOptions() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf((*Message_Broadcast)(nil)),
		reflect.TypeOf((*Message_Synchronizer)(nil)),
	}
}
