// Code generated by Mir codegen. DO NOT EDIT.

package synchronizerpbevents

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/synchronizerpb/types"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func SyncRequest(destModule stdtypes.ModuleID, orphanBlock *types.Block, leaveNodeIds []uint64) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Synchronizer{
			Synchronizer: &types2.Event{
				Type: &types2.Event_SyncRequest{
					SyncRequest: &types2.SyncRequest{
						OrphanBlock:  orphanBlock,
						LeaveNodeIds: leaveNodeIds,
					},
				},
			},
		},
	}
}
